### ISSUE TITLE
testHome fails because of this assert

### ISSUE THREAD

**Issue by SureSRM** [UNIZAR-30246-WebEngineering/UrlShortener#2]
When test executes this statement:
```
 assertThat(entity.getHeaders().getContentType(), is(new MediaType("text", "html")));
```
It compares the expected contentype *<text/html>* with the actual result *<text/html;charset=UTF-8>*

This causes the test fails so I recomend:
A- Delete this assertion
B- Compare it like two plain text ignoring the rest of characters
C- Look for a way to compare this two MediaType objects ignoring the charset

**Comment by fjlopez** [comment]
Fixed with 1588c3a2ffb635d6469257b0273dcf64b3b0978c. Rather than testing equality, the test tests compatibility.
